services:
  service-a:
    build: ./service-a
    ports:
      - "3000:3000"
    depends_on:
      - service-b
    environment:
      - TAX_SERVICE_URL=http://service-b:4000
    networks:
      - tax-network
  service-b:
    build: ./service-b
    ports:
      - "4000:4000"
    networks:
      - tax-network


networks:
  tax-network:
    driver: bridge