apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-spring
  labels:
    app: hello-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-spring
  template:
    metadata:
      name: hello-spring
      labels:
        app: hello-spring
    spec:
      containers:
        - name: hello-spring
          image: embarkx/hello-spring
          env:
            - name: ENV_VALUE
              valueFrom:
                configMapKeyRef:
                  name: hello-spring-config
                  key: ENV_VALUE
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: hello-spring-svc
spec:
  selector:
    app: hello-spring
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
    
      